# Generated by Django 6.0.3 on 2026-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesession_hint_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='submitted_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('cleared', 'Cleared')], default='playing', max_length=20),
        ),
    ]
