# Generated by Django 6.0.3 on 2026-05-22 07:31

from django.db import migrations, models


def seed_turtle_soup_checkpoints(apps, schema_editor):
    Puzzle = apps.get_model("game", "Puzzle")
    checkpoints = "\n".join(
        [
            "남자는 과거 조난 상황에서 수프를 먹었다.",
            "그때 먹은 수프는 바다거북스프가 아니라 인육 수프였다.",
            "식당에서 진짜 바다거북스프를 먹고 과거의 진실을 깨달았다.",
        ]
    )
    Puzzle.objects.filter(title="첫 번째 테스트 문제", answer_checkpoints="").update(
        answer_checkpoints=checkpoints
    )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_cleared_at_gamesession_submitted_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer_checkpoints',
            field=models.TextField(blank=True, help_text='정답으로 인정하기 위해 포함되어야 하는 핵심 조건을 줄마다 하나씩 입력하세요.'),
        ),
        migrations.RunPython(seed_turtle_soup_checkpoints, migrations.RunPython.noop),
    ]
