# Generated by Django 6.0.3 on 2026-05-22 08:05

from django.db import migrations, models


def seed_turtle_soup_question_criteria(apps, schema_editor):
    Puzzle = apps.get_model("game", "Puzzle")
    Puzzle.objects.filter(title="첫 번째 테스트 문제").update(
        question_yes_facts="\n".join(
            [
                "남자는 식당에서 바다거북스프를 먹었다.",
                "남자는 집에 돌아온 뒤 자살했다.",
                "남자는 과거 조난 상황에서 수프를 먹은 적이 있다.",
                "남자는 식당의 수프 맛을 통해 과거의 진실을 깨달았다.",
            ]
        ),
        question_no_facts="\n".join(
            [
                "남자는 다른 사람에게 살해당했다.",
                "남자는 원래 자살 계획이 있었다.",
                "남자는 바다거북스프를 먹기 전부터 자살할 계획이었다.",
                "식당의 수프에는 독이 들어 있었다.",
                "식당에서 먹은 수프는 인육 수프였다.",
            ]
        ),
        question_irrelevant_facts="\n".join(
            [
                "남자의 신발 색깔",
                "남자의 이름",
                "남자의 옷 색깔",
                "식당의 위치",
            ]
        ),
        question_ambiguous_examples="\n".join(
            [
                "남자는 이상한 기분이 들었나요?",
                "남자에게 무언가 일이 있었나요?",
                "그 일이 중요했나요?",
            ]
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_puzzle_answer_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='question_ambiguous_examples',
            field=models.TextField(blank=True, help_text="'질문이 모호합니다'로 답해야 하는 예시를 줄마다 하나씩 입력하세요."),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question_irrelevant_facts',
            field=models.TextField(blank=True, help_text="'관계없습니다'로 답해야 하는 주변 정보를 줄마다 하나씩 입력하세요."),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question_no_facts',
            field=models.TextField(blank=True, help_text="'아닙니다'로 답해야 하는 사실을 줄마다 하나씩 입력하세요."),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question_yes_facts',
            field=models.TextField(blank=True, help_text="'맞습니다'로 답해야 하는 사실을 줄마다 하나씩 입력하세요."),
        ),
        migrations.RunPython(seed_turtle_soup_question_criteria, migrations.RunPython.noop),
    ]
