# Generated by Django 6.0.3 on 2026-05-22 08:26

import django.db.models.deletion
from django.db import migrations, models


def seed_turtle_soup_question_tests(apps, schema_editor):
    Puzzle = apps.get_model("game", "Puzzle")
    QuestionTestCase = apps.get_model("game", "QuestionTestCase")
    puzzle = Puzzle.objects.filter(title="첫 번째 테스트 문제").first()
    if puzzle is None:
        return

    test_cases = [
        ("남자는 식당에서 바다거북스프를 먹었나요?", "맞습니다"),
        ("남자는 집에 돌아온 뒤 자살했나요?", "맞습니다"),
        ("남자는 다른 사람에게 살해당했나요?", "아닙니다"),
        ("남자는 원래 자살 계획이 있었나요?", "아닙니다"),
        ("남자의 신발 색깔이 중요합니까?", "관계없습니다"),
        ("남자는 이상한 기분이 들었나요?", "질문이 모호합니다"),
    ]
    for question_text, expected_label in test_cases:
        QuestionTestCase.objects.get_or_create(
            puzzle=puzzle,
            question_text=question_text,
            defaults={"expected_label": expected_label},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_puzzle_question_ambiguous_examples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('expected_label', models.CharField(choices=[('맞습니다', '맞습니다'), ('아닙니다', '아닙니다'), ('질문이 모호합니다', '질문이 모호합니다'), ('관계없습니다', '관계없습니다')], max_length=20)),
                ('last_answer_label', models.CharField(blank=True, max_length=20)),
                ('last_passed', models.BooleanField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_test_cases', to='game.puzzle')),
            ],
            options={
                'ordering': ['puzzle', 'id'],
            },
        ),
        migrations.RunPython(seed_turtle_soup_question_tests, migrations.RunPython.noop),
    ]
